baseDomain: example.com
autoSignUp: true
httpServer:
  enable: true
  addr: 0.0.0.0:8080
  tls.enable: false
gateServer:
  - name: os_beta01
    title: 127.0.0.1:22101
    dispatchUrl: http://127.0.0.1:8080/query_cur_region
  - name: os_beta02
    title: 127.0.0.1:22102
    addr: 127.0.0.1:22102
gameServer:
  enable: true
  addr: 0.0.0.0:22102
database:
  driver: sqlite
  dsn: file:data/hk4e-emu.db?cache=shared&mode=rwc
